### ISSUE TITLE
lua version and required module

### ISSUE THREAD

**Issue by guojting** [jirenz/HiDDeN#2]
**I have got several questions when I try to run the main.lua. Could you please provide the information of the lua version and the required modules? Thank you. 

I got an error like this:** 
lua: main.lua:6: module './cropout.lua' not found:
        no field package.preload['./cropout.lua']
        no file '/root/.luarocks/share/lua/5.1///cropout/lua.lua'
        no file '/root/.luarocks/share/lua/5.1///cropout/lua/init.lua'
        no file '/root/torch/install/share/lua/5.1///cropout/lua.lua'
        no file '/root/torch/install/share/lua/5.1///cropout/lua/init.lua'
        no file './//cropout/lua.lua'
        no file '/root/torch/install/share/luajit-2.1.0-beta1///cropout/lua.lua'
        no file '/usr/local/share/lua/5.1///cropout/lua.lua'
        no file '/usr/local/share/lua/5.1///cropout/lua/init.lua'
        no file '/root/torch/install/lib///cropout/lua.so'
        no file '/root/.luarocks/lib/lua/5.1///cropout/lua.so'
        no file '/root/torch/install/lib/lua/5.1///cropout/lua.so'
        no file './//cropout/lua.so'
        no file '/usr/local/lib/lua/5.1///cropout/lua.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/root/torch/install/lib/.so'
        no file '/root/.luarocks/lib/lua/5.1/.so'
        no file '/root/torch/install/lib/lua/5.1/.so'
        no file './.so'
        no file '/usr/local/lib/lua/5.1/.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        main.lua:6: in main chunk
        [C]: ?

**Comment by jirenz** [comment]
Sorry, this project used lua torch. [http://torch.ch](http://torch.ch)

**Comment by guojting** [comment]
Thank you! I have got the lua torch. 
Now I can run the test-run experiment.
However, when I try to use GPU like "th main.lua --develop --name test-run -type cuda" , it still runs with CPU.  I have cuda installed. Do you have any idea what is wrong?

**Comment by jirenz** [comment]
I am not sure given the information. Check `opt.type` first. If it is `"cuda"` the code will try to import CUDA related libraries and tell you that CUDA is used.
```
# In main.lua
if opt.type == "cuda" then
	require 'cunn'
	require 'cudnn'
	require 'cutorch'
	print('running with cudnn backend')
	cudnn.benchmark = true
end
```
